name: Go

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 9 * * *"

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Authenticate to Google Cloud
      id: 'google-cloud-auth'
      uses: 'google-github-actions/auth@v0.4.1'
      env:
        YOUTUBE_SERVICE_ACCOUNT: ${{ secrets.YOUTUBE_SERVICE_ACCOUNT }}
      with:
        create_credentials_file: true
        workload_identity_provider: 'projects/227114582793/locations/global/workloadIdentityPools/notion-oidc-pool/providers/notion-oidc-pool'
        service_account: ${{ env.YOUTUBE_SERVICE_ACCOUNT }}

    - name: Google Cloud login
      run: gcloud auth login --brief --cred-file="${{ steps.google-cloud-auth.outputs.credentials_file_path }}"
      
    - name: debug
      run: echo $GOOGLE_APPLICATION_CREDENTIALS && cat $GOOGLE_APPLICATION_CREDENTIALS

    - name: Run
      env:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        YOUTUBE_CLIENT_ID: ${{ secrets.YOUTUBE_CLIENT_ID }}
        YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
      run: go run ./main.go
